# Generated by Django 5.2 on 2025-11-18 05:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp de última modificación', verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre común del artículo', max_length=300, unique=True, verbose_name='Nombre del Artículo')),
                ('codigo', models.CharField(blank=True, db_index=True, help_text='SKU o código interno (auto-generado)', max_length=50, unique=True, verbose_name='Código')),
                ('categoria', models.CharField(choices=[('tecnologia', 'Tecnología'), ('mobiliario', 'Mobiliario'), ('laboratorio', 'Laboratorio'), ('deportes', 'Deportes'), ('audiovisual', 'Audiovisual'), ('libros', 'Libros'), ('herramientas', 'Herramientas'), ('vehiculos', 'Vehículos'), ('otros', 'Otros')], db_index=True, max_length=100, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='articulos/fotos/', verbose_name='Foto')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'inventario_articulo',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_art_nombre'), models.Index(fields=['codigo'], name='idx_art_codigo'), models.Index(fields=['categoria'], name='idx_art_categoria'), models.Index(fields=['categoria', 'nombre'], name='idx_art_cat_nombre'), models.Index(fields=['activo'], name='idx_art_activo')],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp de última modificación', verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre identificativo de la sede', max_length=200, unique=True, verbose_name='Nombre de la Sede')),
                ('codigo', models.CharField(db_index=True, help_text='Código alfanumérico único (ej: SN-001, CENTRAL)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Código debe contener solo mayúsculas, números y guiones', regex='^[A-Z0-9\\-]+$')], verbose_name='Código de Sede')),
                ('direccion', models.CharField(blank=True, help_text='Dirección física de la sede', max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Indica si la sede está operativa', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'inventario_sede',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['nombre'], name='idx_sede_nombre'), models.Index(fields=['codigo'], name='idx_sede_codigo'), models.Index(fields=['activo'], name='idx_sede_activo')],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp de última modificación', verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(help_text='Nombre de la persona', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido de la persona', max_length=100, verbose_name='Apellido')),
                ('tipo_documento', models.CharField(blank=True, choices=[('cc', 'Cédula de Ciudadanía'), ('ti', 'Tarjeta de Identidad'), ('ce', 'Cédula de Extranjería'), ('pas', 'Pasaporte'), ('nit', 'NIT')], max_length=10, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='Número de Documento')),
                ('cargo', models.CharField(blank=True, help_text='Cargo o rol en la institución', max_length=100, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono debe contener solo números, espacios, +, - y ()', regex='^\\+?[0-9\\s\\-()]+$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Correo electrónico único', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables', to='inventario.sede', verbose_name='Sede Asignada')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'db_table': 'inventario_responsable',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp de última modificación', verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(help_text='Código alfanumérico (ej: LAB-101, AULA-2A)', max_length=50, validators=[django.core.validators.RegexValidator(message='Código debe contener solo mayúsculas, números y guiones', regex='^[A-Z0-9\\-]+$')], verbose_name='Código de Ubicación')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la ubicación', max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('aula', 'Aula'), ('laboratorio', 'Laboratorio'), ('oficina', 'Oficina'), ('biblioteca', 'Biblioteca'), ('deposito', 'Depósito'), ('auditorio', 'Auditorio'), ('salon_multiple', 'Salón Múltiple'), ('otro', 'Otro')], db_index=True, max_length=50, verbose_name='Tipo de Ubicación')),
                ('piso', models.IntegerField(blank=True, help_text='Piso o nivel donde se encuentra', null=True, verbose_name='Piso/Nivel')),
                ('capacidad', models.IntegerField(blank=True, help_text='Capacidad de personas/ítems', null=True, verbose_name='Capacidad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='inventario.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'inventario_ubicacion',
                'ordering': ['sede', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp de última modificación', verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(db_index=True, help_text='Código único autogenerado del ítem', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Código debe contener solo mayúsculas, números y guiones', regex='^[A-Z0-9\\-]+$')], verbose_name='Código Interno')),
                ('placa', models.CharField(blank=True, db_index=True, help_text='Placa física del artículo (única si está presente) - CLAUDE.md línea 166', max_length=100, null=True, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(blank=True, help_text='Marca del artículo (lista editable) - CLAUDE.md línea 175', max_length=100, verbose_name='Marca')),
                ('serial', models.CharField(blank=True, help_text='Número de serie (único por artículo) - CLAUDE.md línea 176', max_length=100, verbose_name='Serial')),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], db_index=True, default='bueno', help_text='Condición física: Bueno/Regular/Malo', max_length=20, verbose_name='Estado Físico')),
                ('disponibilidad', models.CharField(choices=[('en_uso', 'En uso'), ('en_reparacion', 'En reparación'), ('extraviado', 'Extraviado'), ('de_baja', 'De baja')], db_index=True, default='en_uso', help_text='Estado operativo: En uso/En reparación/Extraviado/De baja', max_length=20, verbose_name='Disponibilidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_inventario', to='inventario.articulo', verbose_name='Artículo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_asignados', to='inventario.responsable', verbose_name='Responsable Asignado')),
                ('sede', models.ForeignKey(help_text='Derivada de ubicación (redundante por rendimiento)', on_delete=django.db.models.deletion.PROTECT, related_name='items_inventario', to='inventario.sede', verbose_name='Sede')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventario.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Ítems de Inventario',
                'db_table': 'inventario_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp de última modificación', verbose_name='Fecha de actualización')),
                ('tipo_movimiento', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('cambio_ubicacion', 'Cambio de Ubicación'), ('cambio_responsable', 'Cambio de Responsable'), ('cambio_estado', 'Cambio de Estado'), ('eliminacion', 'Eliminación'), ('importacion', 'Importación Excel'), ('exportacion', 'Exportación Excel'), ('batch_update', 'Actualización Masiva')], db_index=True, max_length=50, verbose_name='Tipo de Movimiento')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado antes del cambio', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado después del cambio', null=True, verbose_name='Datos Nuevos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.iteminventario', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Historial de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
                'db_table': 'inventario_historial',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item'], name='idx_hist_item'), models.Index(fields=['tipo_movimiento'], name='idx_hist_tipo'), models.Index(fields=['item', '-created_at'], name='idx_hist_item_fecha'), models.Index(fields=['usuario'], name='idx_hist_usuario')],
            },
        ),
        migrations.AddIndex(
            model_name='responsable',
            index=models.Index(fields=['tipo_documento', 'documento'], name='idx_resp_documento'),
        ),
        migrations.AddIndex(
            model_name='responsable',
            index=models.Index(fields=['email'], name='idx_resp_email'),
        ),
        migrations.AddIndex(
            model_name='responsable',
            index=models.Index(fields=['sede'], name='idx_resp_sede'),
        ),
        migrations.AddIndex(
            model_name='responsable',
            index=models.Index(fields=['activo'], name='idx_resp_activo'),
        ),
        migrations.AddConstraint(
            model_name='responsable',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__isnull', False), ('tipo_documento__isnull', False)), fields=('tipo_documento', 'documento'), name='unique_documento_responsable'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['sede', 'codigo'], name='idx_ubic_sede_codigo'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['tipo'], name='idx_ubic_tipo'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['activo'], name='idx_ubic_activo'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['sede', 'tipo'], name='idx_ubic_sede_tipo'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('sede', 'codigo'), name='unique_codigo_por_sede'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['codigo'], name='idx_item_codigo'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['placa'], name='idx_item_placa'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['estado'], name='idx_item_estado'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['disponibilidad'], name='idx_item_disponib'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['articulo'], name='idx_item_articulo'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['ubicacion'], name='idx_item_ubicacion'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['sede'], name='idx_item_sede'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['responsable'], name='idx_item_responsable'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['marca'], name='idx_item_marca'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['sede', 'disponibilidad'], name='idx_item_sede_disp'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['ubicacion', 'disponibilidad'], name='idx_item_ubic_disp'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['articulo', 'disponibilidad'], name='idx_item_art_disp'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['articulo', 'serial'], name='idx_item_art_serial'),
        ),
        migrations.AddConstraint(
            model_name='iteminventario',
            constraint=models.UniqueConstraint(condition=models.Q(('serial__isnull', False), models.Q(('serial', ''), _negated=True)), fields=('articulo', 'serial'), name='unique_serial_per_articulo'),
        ),
    ]
