# Generated by Django 5.2 on 2025-11-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_make_serial_marca_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='disponibilidad',
            field=models.CharField(db_index=True, default='en_uso', help_text='Estado operativo: En uso/En reparación/Extraviado/De baja', max_length=20, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='estado',
            field=models.CharField(db_index=True, default='bueno', help_text='Condición física: Bueno/Regular/Malo', max_length=20, verbose_name='Estado Físico'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='cargo',
            field=models.CharField(blank=True, choices=[('docente', 'Docente'), ('coordinador', 'Coordinador'), ('rector', 'Rector'), ('auxiliar_administrativo', 'Auxiliar Administrativo'), ('operario_sistema', 'Operario Sistema'), ('otro', 'Otro')], help_text='Cargo o rol en la institución', max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('cc', 'Cédula de Ciudadanía'), ('ti', 'Tarjeta de Identidad'), ('ce', 'Cédula de Extranjería'), ('pas', 'Pasaporte'), ('nit', 'NIT')], max_length=10, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Tipo de Ubicación'),
        ),
    ]
