# Generated by Django 5.2 on 2025-11-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_iteminventario_disponibilidad_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='iteminventario',
            name='unique_serial_per_articulo',
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='serial',
            field=models.CharField(blank=True, help_text='Número de serie', max_length=100, null=True, verbose_name='Serial'),
        ),
    ]
