# Generated by Django 5.2 on 2025-11-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_iteminventario_unique_serial_per_articulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='coordinador',
            field=models.ForeignKey(blank=True, help_text='Responsable coordinador de esta sede', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes_coordinadas', to='inventario.responsable', verbose_name='Coordinador de Sede'),
        ),
    ]
