# Generated by Django 5.2 on 2025-11-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_add_coordinador_to_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='cargo',
            field=models.CharField(blank=True, db_index=True, help_text='Cargo o rol en la institución (valores libres desde Excel)', max_length=100, verbose_name='Cargo'),
        ),
    ]
